import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navabar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Project'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shivang | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </div>
  )
}
